### ISSUE TITLE
Unit Tests para o desafio DSA

### ISSUE THREAD

**Issue by rcr109** [dsacademybr/PythonFundamentos#8]
Boa tarde. No desafio DSA do capitulo 06 são citadas Unit Tests e também arquivos com as respostas do desafio. Não encontrei nenhum deles aqui. Poderiam me ajudar? Grato.

**Comment by weliton-bastos** [comment]
Se entendi direito sua pergunta, tenho que perguntar:

Você baixou todos os arquivos de
https://github.com/dsacademybr/PythonFundamentos ?
Se não, baixe tudo.

O desafio está na pasta Cap07 e a solução na pasta Cap08/DesafioDSA_Solucao

Espero ter ajudado.

Att.
*Weliton Moreira Bastos*

*31/10/2020 - 503 anos da Reforma Protestante. O que estamos fazendo com o
Evangelho?*


Em sáb., 9 de mai. de 2020 às 14:49, rcr109 <notifications@github.com>
escreveu:
